#pragma once

enum GameState
{
	GAME_STATE_IN_GAME,
	GAME_STATE_LOBBY,
	GAME_STATE_PAUSED,
	GAME_STATE_LOADING_TO_GAME,
	GAME_STATE_LOADING_TO_LOBBY,
	GAME_STATE_OPTION_FROM_LOBBY,
	GAME_STATE_OPTION_FROM_PAUSED,
	GAME_STATE_CHECK_EXIT_FROM_LOBBY_TO_WINDOWS,
	GAME_STATE_CHECK_EXIT_FROM_PAUSED_TO_WINDOWS,
	GAME_STATE_CHECK_EXIT_FROM_PAUSED_TO_LOBBY,
	GAME_STATE_TERMINATE
};